### ISSUE TITLE
Sliders for each tab don't change

### ISSUE THREAD

**Issue by Ambercroft** [vzze/volume-control#1]
Installed the add-in Firefox 109.0.1 64 bit Windows 10
When I click on the icon in the tool bar the 2 tabs that have sound show. Similar as the Readme file.
Each slider can move but the sound does not change and the number stays at 100.
Any suggestions would be helpful. 

This is exactly the add-on I want. I just need the solution to get it operating.

Thanks

**Comment by vzze** [comment]
The extension works fine for me, I am using Firefox Dev Edition 110.0.
Have you tried only having volume-control loaded and nothing else?

**Comment by Ambercroft** [comment]
Update: Installed on my Slackware V14 with the same version of FireFox and works as expected. 
The Windows system has many tabs open that I can not close right now. This may be an issue that I need all of them to be closed first? I will try some other ideas an report what does / not work.

**Comment by vzze** [comment]
The extension was tested only on Windows, if its related to the fact that the "Windows system has many tabs open" then there could be a problem with the browser's sync storage

**Comment by Ambercroft** [comment]
Tried closing Firefox and reopening - no change
Closed Tabs one at a time and began working after only 3 tabs remained.  - Solved
Opening many tabs did not stop the extension from working!
The Slackware system only had 2 tabs open, so unsure if it would have the same issue with high quantity of tabs open before first run.

Add to the docs that all tabs should be closed before starting the first time.

**Comment by vzze** [comment]
Thanks for the feedback! Added this in the about section of the extension.
