### ISSUE TITLE
Add pause

### ISSUE THREAD

**Issue by Davilarek** [vzze/volume-control#3]
Hello, thanks for the addon.
It would be cool to see a pause button for each tab.

**Comment by vzze** [comment]
You can check out the latest commit if you want to test it out, I'll update the version on the Firefox store in a couple of hours.

**Comment by Davilarek** [comment]
Awesome 👍 
Also, you can use Github Actions to make the zip automatically, I can make a pr for this

**Comment by vzze** [comment]
That would be amazing, thanks for the help again :)
